const footballDB = db.getSiblingDB('football_db')

// Очистка коллекций
footballDB.players.drop()
footballDB.matches.drop()
footballDB.users.drop()
print('Коллекции очищены\n')

//  Коллекция: players
footballDB.players.insertMany([
	{
		name: 'Lionel Messi',
		age: 37,
		nationality: 'Argentina',
		position: 'Forward',
		team: 'Inter Miami',
		height_cm: 170,
		weight_kg: 72,
		jerseyNumber: 10,
		transfers: [
			{ from: 'Barcelona', to: 'PSG', year: 2021 },
			{ from: 'PSG', to: 'Inter Miami', year: 2023 },
		],
		stats: {
			goals: 850,
			assists: 370,
			yellowCards: 70,
			redCards: 3,
			minutesPlayed: 68400,
		},
		achievements: ["Ballon d'Or x8", 'World Cup 2022', 'Copa America 2021'],
		comments: [
			{
				author: 'fan_arg',
				text: 'Лучший игрок в истории футбола!',
				date: '2024-03-10',
				banned: false,
			},
			{
				author: 'analyst_pro',
				text: 'Его видение поля не поддаётся описанию.',
				date: '2024-04-01',
				banned: false,
			},
		],
	},
	{
		name: 'Cristiano Ronaldo',
		age: 39,
		nationality: 'Portugal',
		position: 'Forward',
		team: 'Al Nassr',
		height_cm: 187,
		weight_kg: 84,
		jerseyNumber: 7,
		transfers: [
			{ from: 'Sporting CP', to: 'Manchester United', year: 2003 },
			{ from: 'Manchester United', to: 'Real Madrid', year: 2009 },
			{ from: 'Real Madrid', to: 'Juventus', year: 2018 },
			{ from: 'Juventus', to: 'Manchester United', year: 2021 },
			{ from: 'Manchester United', to: 'Al Nassr', year: 2023 },
		],
		stats: {
			goals: 895,
			assists: 260,
			yellowCards: 115,
			redCards: 11,
			minutesPlayed: 76000,
		},
		achievements: ["Ballon d'Or x5", 'UCL x5', 'Euro 2016'],
		comments: [
			{
				author: 'cr7_fan',
				text: 'GOAT без сомнений. Siuuuu!',
				date: '2024-02-14',
				banned: false,
			},
		],
	},
	{
		name: 'Kylian Mbappé',
		age: 25,
		nationality: 'France',
		position: 'Forward',
		team: 'Real Madrid',
		height_cm: 178,
		weight_kg: 73,
		jerseyNumber: 9,
		transfers: [
			{ from: 'Monaco', to: 'PSG', year: 2018 },
			{ from: 'PSG', to: 'Real Madrid', year: 2024 },
		],
		stats: {
			goals: 310,
			assists: 180,
			yellowCards: 35,
			redCards: 1,
			minutesPlayed: 29000,
		},
		achievements: ['World Cup 2018', 'Ligue 1 x6'],
		comments: [
			{
				author: 'speed_lover',
				text: 'Быстрее всех на планете. Будущее футбола.',
				date: '2024-05-20',
				banned: false,
			},
			{
				author: 'troll_user',
				text: 'Переоценённый игрок!!!',
				date: '2024-05-21',
				banned: true,
			},
		],
	},
	{
		name: 'Erling Haaland',
		age: 23,
		nationality: 'Norway',
		position: 'Forward',
		team: 'Manchester City',
		height_cm: 194,
		weight_kg: 88,
		jerseyNumber: 9,
		transfers: [
			{ from: 'Molde', to: 'RB Salzburg', year: 2019 },
			{ from: 'RB Salzburg', to: 'Borussia Dortmund', year: 2020 },
			{ from: 'Borussia Dortmund', to: 'Manchester City', year: 2022 },
		],
		stats: {
			goals: 215,
			assists: 55,
			yellowCards: 20,
			redCards: 0,
			minutesPlayed: 18500,
		},
		achievements: ['Premier League 2023', 'Treble 2023'],
		comments: [
			{
				author: 'goal_machine',
				text: 'Машина для голов. Такого центрфорварда не было давно.',
				date: '2024-01-30',
				banned: false,
			},
		],
	},
	{
		name: 'Luka Modrić',
		age: 38,
		nationality: 'Croatia',
		position: 'Midfielder',
		team: 'Real Madrid',
		height_cm: 172,
		weight_kg: 66,
		jerseyNumber: 10,
		transfers: [
			{ from: 'Dinamo Zagreb', to: 'Tottenham', year: 2008 },
			{ from: 'Tottenham', to: 'Real Madrid', year: 2012 },
		],
		stats: {
			goals: 45,
			assists: 160,
			yellowCards: 90,
			redCards: 2,
			minutesPlayed: 58000,
		},
		achievements: ["Ballon d'Or 2018", 'UCL x6', 'World Cup Finalist 2018'],
		comments: [
			{
				author: 'midfield_fan',
				text: 'Лучший полузащитник поколения. Элегантность в каждом касании.',
				date: '2024-02-28',
				banned: false,
			},
		],
	},
	{
		name: 'Vinicius Junior',
		age: 23,
		nationality: 'Brazil',
		position: 'Winger',
		team: 'Real Madrid',
		height_cm: 176,
		weight_kg: 73,
		jerseyNumber: 7,
		transfers: [{ from: 'Flamengo', to: 'Real Madrid', year: 2018 }],
		stats: {
			goals: 105,
			assists: 95,
			yellowCards: 45,
			redCards: 1,
			minutesPlayed: 22000,
		},
		achievements: ['UCL 2022', 'UCL 2024', 'La Liga x2'],
		comments: [
			{
				author: 'real_fan_madrid',
				text: 'Vinicius — это магия на левом фланге!',
				date: '2024-06-01',
				banned: false,
			},
		],
	},
])
print('players: ' + footballDB.players.countDocuments() + ' документов')

//  Коллекция: matches
footballDB.matches.insertMany([
	{
		homeTeam: 'Real Madrid',
		awayTeam: 'Barcelona',
		date: '2024-10-26',
		tournament: 'La Liga',
		season: '2024/2025',
		stadium: 'Santiago Bernabéu',
		attendance: 81044,
		score: { home: 4, away: 0 },
		lineups: {
			home: [
				'Courtois',
				'Carvajal',
				'Militão',
				'Rüdiger',
				'Mendy',
				'Modrić',
				'Kroos',
				'Valverde',
				'Vinicius',
				'Mbappé',
				'Bellingham',
			],
			away: [
				'Ter Stegen',
				'Koundé',
				'Araújo',
				'Martínez',
				'Balde',
				'Pedri',
				'Gavi',
				'De Jong',
				'Yamal',
				'Lewandowski',
				'Raphinha',
			],
		},
		events: [
			{
				type: 'goal',
				player: 'Vinicius Junior',
				team: 'Real Madrid',
				minute: 14,
			},
			{ type: 'yellowCard', player: 'Gavi', team: 'Barcelona', minute: 27 },
			{
				type: 'goal',
				player: 'Kylian Mbappé',
				team: 'Real Madrid',
				minute: 35,
			},
			{
				type: 'substitution',
				playerOut: 'Pedri',
				playerIn: 'Fermín López',
				team: 'Barcelona',
				minute: 46,
			},
			{ type: 'goal', player: 'Luka Modrić', team: 'Real Madrid', minute: 58 },
			{
				type: 'redCard',
				player: 'Ronald Araújo',
				team: 'Barcelona',
				minute: 67,
			},
			{
				type: 'goal',
				player: 'Kylian Mbappé',
				team: 'Real Madrid',
				minute: 82,
			},
		],
		comments: [
			{
				author: 'clasico_watcher',
				text: 'Исторический разгром! Мадрид был великолепен.',
				date: '2024-10-26',
				banned: false,
			},
		],
	},
	{
		homeTeam: 'Manchester City',
		awayTeam: 'Arsenal',
		date: '2024-09-22',
		tournament: 'Premier League',
		season: '2024/2025',
		stadium: 'Etihad Stadium',
		attendance: 53400,
		score: { home: 2, away: 2 },
		lineups: {
			home: [
				'Ederson',
				'Walker',
				'Dias',
				'Akanji',
				'Gvardiol',
				'Rodri',
				'De Bruyne',
				'Bernardo Silva',
				'Doku',
				'Haaland',
				'Foden',
			],
			away: [
				'Raya',
				'White',
				'Saliba',
				'Gabriel',
				'Zinchenko',
				'Rice',
				'Partey',
				'Ødegaard',
				'Saka',
				'Havertz',
				'Martinelli',
			],
		},
		events: [
			{
				type: 'goal',
				player: 'Erling Haaland',
				team: 'Manchester City',
				minute: 10,
			},
			{ type: 'goal', player: 'Bukayo Saka', team: 'Arsenal', minute: 24 },
			{
				type: 'yellowCard',
				player: 'Rodri',
				team: 'Manchester City',
				minute: 38,
			},
			{ type: 'goal', player: 'Kai Havertz', team: 'Arsenal', minute: 51 },
			{
				type: 'substitution',
				playerOut: 'Doku',
				playerIn: 'Gündogan',
				team: 'Manchester City',
				minute: 60,
			},
			{
				type: 'goal',
				player: 'Erling Haaland',
				team: 'Manchester City',
				minute: 78,
			},
		],
		comments: [
			{
				author: 'epl_analyst',
				text: 'Ничья в таком матче — справедливый результат.',
				date: '2024-09-22',
				banned: false,
			},
		],
	},
	{
		homeTeam: 'Bayern Munich',
		awayTeam: 'Borussia Dortmund',
		date: '2024-11-02',
		tournament: 'Bundesliga',
		season: '2024/2025',
		stadium: 'Allianz Arena',
		attendance: 75000,
		score: { home: 3, away: 1 },
		lineups: {
			home: [
				'Neuer',
				'Kimmich',
				'Upamecano',
				'Kim',
				'Davies',
				'Goretzka',
				'Musiala',
				'Müller',
				'Gnabry',
				'Kane',
				'Sané',
			],
			away: [
				'Kobel',
				'Ryerson',
				'Hummels',
				'Schlotterbeck',
				'Maatsen',
				'Emre Can',
				'Brandt',
				'Sancho',
				'Reus',
				'Füllkrug',
				'Adeyemi',
			],
		},
		events: [
			{ type: 'goal', player: 'Harry Kane', team: 'Bayern Munich', minute: 8 },
			{
				type: 'goal',
				player: 'Jadon Sancho',
				team: 'Borussia Dortmund',
				minute: 31,
			},
			{
				type: 'yellowCard',
				player: 'Emre Can',
				team: 'Borussia Dortmund',
				minute: 44,
			},
			{
				type: 'goal',
				player: 'Jamal Musiala',
				team: 'Bayern Munich',
				minute: 55,
			},
			{
				type: 'substitution',
				playerOut: 'Gnabry',
				playerIn: 'Coman',
				team: 'Bayern Munich',
				minute: 62,
			},
			{ type: 'goal', player: 'Harry Kane', team: 'Bayern Munich', minute: 88 },
		],
		comments: [],
	},
	{
		homeTeam: 'PSG',
		awayTeam: 'Marseille',
		date: '2024-09-15',
		tournament: 'Ligue 1',
		season: '2024/2025',
		stadium: 'Parc des Princes',
		attendance: 47929,
		score: { home: 3, away: 0 },
		lineups: {
			home: [
				'Donnarumma',
				'Hakimi',
				'Marquinhos',
				'Pacho',
				'Nuno Mendes',
				'Vitinha',
				'Ruiz',
				'Lee',
				'Dembélé',
				'Ramos',
				'Barcola',
			],
			away: [
				'Rulli',
				'Clauss',
				'Balerdi',
				'Gigot',
				'Lodi',
				'Koné',
				'Veretout',
				'Harit',
				'Greenwood',
				'Aubameyang',
				'Ndiaye',
			],
		},
		events: [
			{ type: 'goal', player: 'Gonçalo Ramos', team: 'PSG', minute: 19 },
			{
				type: 'yellowCard',
				player: 'Leonardo Balerdi',
				team: 'Marseille',
				minute: 33,
			},
			{ type: 'goal', player: 'Ousmane Dembélé', team: 'PSG', minute: 47 },
			{
				type: 'substitution',
				playerOut: 'Lee',
				playerIn: 'Asensio',
				team: 'PSG',
				minute: 65,
			},
			{
				type: 'redCard',
				player: 'Valentin Rongier',
				team: 'Marseille',
				minute: 72,
			},
			{ type: 'goal', player: 'Bradley Barcola', team: 'PSG', minute: 85 },
		],
		comments: [
			{
				author: 'ligue1_fan',
				text: 'Le Classique всегда горячий. ПСЖ доминировал весь матч.',
				date: '2024-09-15',
				banned: false,
			},
			{
				author: 'spam_bot',
				text: 'Купи ставки тут site.ru',
				date: '2024-09-15',
				banned: true,
			},
		],
	},
	{
		homeTeam: 'Inter Milan',
		awayTeam: 'AC Milan',
		date: '2024-10-05',
		tournament: 'Serie A',
		season: '2024/2025',
		stadium: 'San Siro',
		attendance: 75817,
		score: { home: 2, away: 3 },
		lineups: {
			home: [
				'Sommer',
				'Pavard',
				'de Vrij',
				'Bastoni',
				'Darmian',
				'Barella',
				'Çalhanoğlu',
				'Mkhitaryan',
				'Dumfries',
				'Lautaro',
				'Thuram',
			],
			away: [
				'Maignan',
				'Emerson',
				'Tomori',
				'Thiaw',
				'Hernández',
				'Musah',
				'Reijnders',
				'Fofana',
				'Chukwueze',
				'Morata',
				'Leão',
			],
		},
		events: [
			{
				type: 'goal',
				player: 'Lautaro Martínez',
				team: 'Inter Milan',
				minute: 11,
			},
			{ type: 'goal', player: 'Álvaro Morata', team: 'AC Milan', minute: 28 },
			{
				type: 'goal',
				player: 'Marcus Thuram',
				team: 'Inter Milan',
				minute: 39,
			},
			{
				type: 'yellowCard',
				player: 'Nicolò Barella',
				team: 'Inter Milan',
				minute: 52,
			},
			{ type: 'goal', player: 'Rafael Leão', team: 'AC Milan', minute: 61 },
			{
				type: 'substitution',
				playerOut: 'Morata',
				playerIn: 'Giroud',
				team: 'AC Milan',
				minute: 68,
			},
			{ type: 'goal', player: 'Rafael Leão', team: 'AC Milan', minute: 79 },
			{ type: 'goal', player: 'Álvaro Morata', team: 'AC Milan', minute: 90 },
		],
		comments: [
			{
				author: 'derby_king',
				text: 'Derby della Madonnina в лучшем виде! Сумасшедший матч.',
				date: '2024-10-05',
				banned: false,
			},
		],
	},
	{
		homeTeam: 'Liverpool',
		awayTeam: 'Chelsea',
		date: '2024-10-19',
		tournament: 'Premier League',
		season: '2024/2025',
		stadium: 'Anfield',
		attendance: 53394,
		score: { home: 1, away: 1 },
		lineups: {
			home: [
				'Alisson',
				'Alexander-Arnold',
				'Konaté',
				'Van Dijk',
				'Robertson',
				'Mac Allister',
				'Gravenberch',
				'Szoboszlai',
				'Salah',
				'Núñez',
				'Díaz',
			],
			away: [
				'Sánchez',
				'Gusto',
				'Chalobah',
				'Colwill',
				'Cucurella',
				'Caicedo',
				'Enzo',
				'Palmer',
				'Sterling',
				'Jackson',
				'Mudryk',
			],
		},
		events: [
			{ type: 'goal', player: 'Mohamed Salah', team: 'Liverpool', minute: 33 },
			{
				type: 'yellowCard',
				player: 'Enzo Fernández',
				team: 'Chelsea',
				minute: 55,
			},
			{
				type: 'substitution',
				playerOut: 'Mudryk',
				playerIn: 'Nkunku',
				team: 'Chelsea',
				minute: 63,
			},
			{ type: 'goal', player: 'Cole Palmer', team: 'Chelsea', minute: 74 },
		],
		comments: [
			{
				author: 'anfield_roar',
				text: 'Энфилд всегда атмосферный, но хотелось бы победы.',
				date: '2024-10-19',
				banned: false,
			},
		],
	},
])
print('matches: ' + footballDB.matches.countDocuments() + ' документов')

print('\nБаза данных football_db успешно инициализирована!')

//  Коллекция: users
footballDB.users.insertMany([
	{
		username: 'fan_arg',
		email: 'argentina_fan@mail.com',
		passwordHash:
			'$2b$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ123456',
		role: 'user',
		registeredAt: '2022-11-15',
		lastLogin: '2024-10-26',
		isBanned: false,
		favoriteTeam: 'Inter Miami',
		commentCount: 24,
		activity: { commentsLeft: 24, matchesWatched: 137, predictionsCorrect: 45 },
	},
	{
		username: 'analyst_pro',
		email: 'analyst@footballstats.com',
		passwordHash:
			'$2b$10$zyxwvutsrqponmlkjihggfZYXWVUTSRQPONMLKJIHGFEDCBA654321',
		role: 'moderator',
		registeredAt: '2021-03-20',
		lastLogin: '2024-10-27',
		isBanned: false,
		favoriteTeam: 'Barcelona',
		commentCount: 312,
		activity: {
			commentsLeft: 312,
			matchesWatched: 540,
			predictionsCorrect: 210,
		},
	},
	{
		username: 'clasico_watcher',
		email: 'clasico@gmail.com',
		passwordHash:
			'$2b$10$qwertyuiopasdfghjklzxcQWERTYUIOPASDFGHJKLZXCVBNM112233',
		role: 'user',
		registeredAt: '2023-08-01',
		lastLogin: '2024-10-26',
		isBanned: false,
		favoriteTeam: 'Real Madrid',
		commentCount: 87,
		activity: { commentsLeft: 87, matchesWatched: 203, predictionsCorrect: 88 },
	},
	{
		username: 'admin_football',
		email: 'admin@footballdb.com',
		passwordHash:
			'$2b$10$mnbvcxzlkjhgfdsapoiuytrMNBVCXZLKJHGFDSAPOIUYTREWQ998877',
		role: 'admin',
		registeredAt: '2020-01-01',
		lastLogin: '2024-10-27',
		isBanned: false,
		favoriteTeam: null,
		commentCount: 5,
		activity: { commentsLeft: 5, matchesWatched: 999, predictionsCorrect: 0 },
	},
	{
		username: 'troll_user',
		email: 'troll@troll.net',
		passwordHash:
			'$2b$10$trolololololololololollTROLOLOLOLOLOLOLOLOLOLOL000000',
		role: 'user',
		registeredAt: '2024-05-19',
		lastLogin: '2024-05-21',
		isBanned: true,
		banReason: 'Систематические оскорбления и спам в комментариях',
		bannedAt: '2024-05-22',
		bannedBy: 'admin_football',
		favoriteTeam: 'PSG',
		commentCount: 3,
		activity: { commentsLeft: 3, matchesWatched: 12, predictionsCorrect: 1 },
	},
	{
		username: 'epl_analyst',
		email: 'epl_stats@outlook.com',
		passwordHash:
			'$2b$10$epleplepleplepleplepleplEPLEPLEPLEPLEPLEPLEPLEPL445566',
		role: 'moderator',
		registeredAt: '2022-07-10',
		lastLogin: '2024-09-23',
		isBanned: false,
		favoriteTeam: 'Manchester City',
		commentCount: 198,
		activity: {
			commentsLeft: 198,
			matchesWatched: 380,
			predictionsCorrect: 155,
		},
	},
	{
		username: 'derby_king',
		email: 'derby@serie-a.it',
		passwordHash:
			'$2b$10$derbyderbyderbyderbyderbDERBYDERBYDERBYDERBYDERBY778899',
		role: 'user',
		registeredAt: '2023-01-15',
		lastLogin: '2024-10-06',
		isBanned: false,
		favoriteTeam: 'Inter Milan',
		commentCount: 56,
		activity: { commentsLeft: 56, matchesWatched: 95, predictionsCorrect: 40 },
	},
])
print('users: ' + footballDB.users.countDocuments() + ' документов')
